from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
from time import sleep
from Locators import *
from Pages.Financial_Manager.Report import Report
from Pages.Login import LoginPage
import unittest

# driver = webdriver.Chrome(ChromeDriverManager().install())
from selenium.webdriver.chrome.service import Service
service = Service()
options = webdriver.ChromeOptions()
driver = webdriver.Chrome(service=service, options=options)


class Test_bpm(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.driver = driver
        cls.driver.maximize_window()
        cls.driver.implicitly_wait(5)

################### login_financial_manager ###################

    def test01_login_financial_manager(self):
        self.driver.get(base_url)
        login = LoginPage(driver=self.driver)
        login.enter_login_username(account_financial)
        login.enter_login_btn_submit_next()
        login.enter_login_password(code_no_admin)
        login.enter_login_btn_submit()
        print("با موفقیت وارد پنل اکانت مالی شد")
        print("############################################")

################### financial_manager_report_check ###################

    def test02_financial_manager_report_check(self):
        report = Report(driver=self.driver)
        report.enter_report()
        report.enter_report_manager_check()
        report.enter_len_report_manager_check()
        print("############################################")

################### financial_manager_reports ###################

    def test03_financial_manager_reports(self):
        report = Report(driver=self.driver)
        report.enter_report()
        report.enter_admin_report_select_the_report147()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        # report.enter_admin_report_select_the_report147_check_table()
        report.enter_report()
        report.enter_admin_report_select_the_report148()
        report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report148_check_table()
        report.enter_report()
        report.enter_admin_report_select_the_report146()
        report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report146_check_table()
        report.enter_report()
        report.enter_admin_report_select_the_report149()
        report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report149_check_table()
        report.enter_report()
        report.enter_admin_report_select_the_report_new()
        report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report_new_check_table()
        report.enter_report()
        report.enter_admin_report_select_the_report150()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report150_check_table()
        report.enter_report()
        report.enter_admin_report_select_the_report151()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report151_check_table()
        report.enter_report()
        report.enter_admin_report_select_the_report152()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report152_check_table()
        report.enter_report()
        report.enter_admin_report_select_the_report154()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report154_check_table()
        report.enter_report()
        report.enter_admin_report_arian_management_report1()
        report.enter_admin_report_arian_management_report1_document_type()
        report.enter_admin_report_arian_management_report1_created_by_check()
        report.enter_admin_report_arian_management_report1_check_table()
        report.enter_admin_report_filter()
        report.enter_report()
        report.enter_admin_report_arian_management_report2()
        report.enter_admin_report_filter()
        report.enter_admin_report_arian_management_report2_check_table()
        a = report.enter_admin_report_arian_management_report2_batch()
        report.enter_admin_report_reports_search(a)
        report.enter_admin_report_arian_management_report2_check_batch(a)
        report.enter_report()
        report.enter_admin_report_arian_management_report3()
        # report.enter_admin_report_filter()
        report.enter_admin_report_arian_management_report3_check_table()
        report.enter_report()
        report.enter_admin_report_arian_management_report4()
        report.enter_admin_report_filter()
        report.enter_admin_report_arian_management_report4_check_table()
        report.enter_report()
        report.enter_admin_report_arian_management_report5()
        report.enter_admin_report_filter()
        report.enter_admin_report_arian_management_report5_check_table()
        report.enter_admin_report_arian_management_report5_created_by_check()
        report.enter_report()
        report.enter_admin_report_arian_management_report6()
        report.enter_admin_report_arian_management_report6_check_table()
        # report.enter_admin_report_filter()
        report.enter_report()
        report.enter_admin_report_arian_management_report7()
        report.enter_admin_report_arian_management_report7_check_table()
        # report.enter_admin_report_filter()
        report.enter_report()
        report.enter_admin_report_arian_management_report8()
        report.enter_admin_report_arian_management_report8_check_table()
        # report.enter_admin_report_filter()
        report.enter_report()
        report.enter_admin_report_arian_management_report9()
        report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_arian_management_report9_check_table()
        report.enter_report()
        report.enter_admin_report_select_the_report98()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report98_check_table1()
        report.enter_admin_report_select_the_report98_check_table2()
        report.enter_report()
        report.enter_admin_report_select_the_report11()
        report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report11_check_table()
        report.enter_report()
        report.enter_admin_report_select_the_report33()
        report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report33_check_table()
        report.enter_report()
        report.enter_admin_report_select_the_report31()
        report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report31_check_table()
        report.enter_report()
        report.enter_admin_report_select_the_report21()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report21_check_table()
        report.enter_report()
        report.enter_admin_report_select_the_report115()
        report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report115_check_table()
        report.enter_report()
        report.enter_admin_report_select_the_report76()
        report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report76_check_table()
        a = report.enter_admin_report_select_the_report02_tn()
        report.enter_admin_report_reports_search_tn(a)
        report.enter_admin_report_select_the_report22_tn_assert_search()
        report.enter_admin_report_reports_search_tn("")
        report.enter_admin_report_select_the_report76_status_check()
        report.enter_report()
        report.enter_admin_report_select_the_report79()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report79_check_table()
        report.enter_report()
        report.enter_admin_report_select_the_report23()
        # report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report23_check_table()
        report.enter_report()
        report.enter_admin_report_select_the_report36()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report36_check_table()
        report.enter_report()
        report.enter_admin_report_select_the_report20()
        report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report20_check_table()
        a = report.enter_admin_report_select_the_report02_tn()
        report.enter_admin_report_reports_search_tn(a)
        report.enter_admin_report_select_the_report20_tn_assert_search()
        report.enter_admin_report_reports_search_tn("")
        report.enter_admin_report_select_the_report20_status_check()
        report.enter_admin_report_select_the_report20_destination_filter()
        report.enter_report()
        report.enter_admin_report_select_the_report77()
        report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report77_check_table1()
        report.enter_admin_report_select_the_report77_check_table2()
        b = report.enter_admin_report_select_the_report02_tn()
        report.enter_admin_report_reports_search_tn(b)
        report.enter_admin_report_select_the_report26_tn_assert_search()
        report.enter_admin_report_reports_search_tn("")
        sleep(1)
        report.enter_admin_report_select_the_report77_status_check()
        report.enter_report()
        report.enter_admin_report_select_the_report133()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report133_check_table()
        report.enter_report()
        report.enter_admin_report_select_the_report82()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        # report.enter_admin_report_select_the_report82_check_table()
        report.enter_report()
        report.enter_admin_report_select_the_report_fleet_costs()
        report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report_fleet_costs_check_table()
        report.enter_report()
        report.enter_admin_report_select_the_report144()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report144_check_table()
        report.enter_report()
        report.enter_admin_report_select_the_report17()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report17_check_table()
        report.enter_report()
        report.enter_admin_report_select_the_report49()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report49_check_table()
        report.enter_report()
        report.enter_admin_report_select_the_report61()
        report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report61_check_table()
        report.enter_admin_report_arian_management_report5_created_by_check()
        report.enter_admin_report_select_the_report61_document_type_check()
        report.enter_admin_report_select_the_report61_inquery_type_check()
        report.enter_report()
        report.enter_admin_report_select_the_report53()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report53_check_table()
        report.enter_report()
        report.enter_admin_report_select_the_report27()
        report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report27_check_table()
        a = report.enter_admin_report_select_the_report02_tn()
        report.enter_admin_report_reports_search_tn(a)
        # report.enter_admin_report_select_the_report26_tn_assert_search()
        # report.enter_admin_report_reports_search_tn("")
        report.enter_report()
        report.enter_admin_report_select_the_report59()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report59_check_table()
        report.enter_report()
        report.enter_admin_report_select_the_report54()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report54_check_table()
        report.enter_report()
        report.enter_admin_report_select_the_report113()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report113_check_table()
        report.enter_report()
        report.enter_admin_report_select_the_report18()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report18_check_table()
        report.enter_report()
        report.enter_admin_report_select_the_report28()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report28_check_table()
        report.enter_report()
        report.enter_admin_report_select_the_report109()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report109_check_table()
        report.enter_report()
        report.enter_admin_report_select_the_report138()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report138_check_table()
        report.enter_report()
        report.enter_admin_report_select_the_report66()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report66_check_table()
        report.enter_report()
        report.enter_admin_report_select_the_report64()
        report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report64_check_table()
        report.enter_report()
        report.enter_admin_report_select_the_report65()
        report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report65_check_table()
        report.enter_report()
        report.enter_admin_report_select_the_report140()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report140_check_table()
        report.enter_report()
        report.enter_admin_report_select_the_report134()
        report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report134_check_table()
        report.enter_admin_report_select_the_report134_cost_type()
        report.enter_admin_report_select_the_report134_other_inquery_type()
        report.enter_report()
        report.enter_admin_report_select_the_report125()
        report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report125_check_table()
        b = report.enter_admin_report_select_the_report75_tn()
        # report.enter_admin_report_reports_search_tn(b)
        # report.enter_admin_report_select_the_report02_tn_assert_search()
        report.enter_admin_report_reports_search_tn("")
        report.enter_admin_report_select_the_report09_status_check()
        report.enter_admin_report_select_the_report20_destination_filter()
        report.enter_report()
        report.enter_admin_report_select_the_report08()
        report.enter_admin_report_filter()
        report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report08_check_table()
        # report.enter_report()
        # report.enter_admin_report_select_the_report145()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        # report.enter_admin_report_select_the_report145_check_table()
        report.enter_report()
        report.enter_admin_report_select_the_report136()
        report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report136_check_table()
        b = report.enter_admin_report_select_the_report02_tn()
        report.enter_admin_report_reports_search_tn(b)
        # report.enter_admin_report_select_the_report22_tn_assert_search()
        report.enter_report()
        report.enter_admin_report_select_the_report123()
        # report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report123_check_table()
        report.enter_report()
        report.enter_admin_report_select_the_report116()
        report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report116_check_table()
        report.enter_report()
        report.enter_admin_report_select_the_report108()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report108_check_table()
        report.enter_report()
        report.enter_admin_report_select_the_report110()
        # report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report110_check_table()
        report.enter_report()
        report.enter_admin_report_select_the_report120()
        report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report120_check_table()
        report.enter_report()
        # report.enter_admin_report_select_the_report40()
        # report.enter_report()
        report.enter_admin_report_select_the_report96()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report96_check_table()
        report.enter_report()
        report.enter_admin_report_select_the_report97()
        # report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report97_check_table()
        report.enter_report()
        report.enter_admin_report_select_the_report03()
        # report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report03_check_table()
        report.enter_report()
        report.enter_admin_report_select_the_report92()
        # report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report92_check_table()
        report.enter_report()
        report.enter_admin_report_select_the_report88()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report88_check_table()
        report.enter_report()
        print("############################################")

    @classmethod
    def tearDownClass(cls) -> None:
        sleep(5)
        cls.driver.close()
        cls.driver.quit()
