from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
from time import sleep

from Locators import *
from Pages.Admin.Admin import Admin
from Pages.Admin.Report import Report
from Pages.Delivery_Manager.Delivery_Manager import Delivery
from Pages.Login import LoginPage
from Pages.Customer_Manager.Orders_Create import Orders_Create
from Pages.Clearance_Inquery import Clearance_Inquery
import unittest

from Pages.Warehouses.Warehouses import Warehouses

# driver = webdriver.Chrome(ChromeDriverManager().install())
from selenium.webdriver.chrome.service import Service
service = Service()
options = webdriver.ChromeOptions()
# options.add_argument("--headless")

driver = webdriver.Chrome(service=service, options=options)


class Test_bpm(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.driver = driver
        cls.driver.maximize_window()
        cls.driver.implicitly_wait(5)

################### login_admin ###################

    def test01_login_admin(self):
        self.driver.get(base_url)
        login = LoginPage(driver=self.driver)
        login.enter_login_username(account_admin02)
        login.enter_login_btn_submit_next()
        login.enter_login_password(code_admin)
        login.enter_login_btn_submit()
        print("با موفقیت وارد پنل ادمین شد")
        print("############################################")

################### admin_report_select_the_reports ###################

    def test02_admin_report_select_the_reports(self):
        report = Report(driver=self.driver)
        # report.enter_admin_report()
        # report.enter_admin_report_select_the_report31()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        # report.enter_admin_report_select_the_report31_check_table()
        # report.enter_admin_report()
        # report.enter_admin_report_select_the_report32()
        # # report.enter_admin_report_filter()
        # # report.enter_admin_report_check_excel()
        # report.enter_admin_report_select_the_report32_check_table()
        # report.enter_admin_report()
        # report.enter_admin_report_select_the_report33()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        # report.enter_admin_report_select_the_report33_check_table()
        # report.enter_admin_report()
        # report.enter_admin_report_select_the_report34()
        # # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        # report.enter_admin_report_select_the_report34_check_table()
        # a = report.enter_admin_report_select_the_report34_tn()
        # report.enter_admin_report_select_the_report30_search(a)
        # # report.enter_admin_report_select_the_report34_tn_assert_search()
        ## report.enter_admin_report()
        ## report.enter_admin_report_select_the_report35()
        ## report.enter_admin_report_filter()
        ## report.enter_admin_report_check_excel()
        ## report.enter_admin_report_select_the_report35_check_table()
        ## a = report.enter_admin_report_select_the_report35_tn()
        ## report.enter_admin_report_reports_search_tn(a)
        ## report.enter_admin_report_select_the_report34_tn_assert_search()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report36()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report36_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report37()
        report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report37_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report39()
        report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report39_check_table()
        report.enter_admin_report_reports_search_tn("Jim Jim")
        report.enter_admin_report_select_the_report26_tn_assert_search()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report41()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report41_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report42()
        report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report42_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report43()
        # report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report43_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report44()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report44_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report45()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report45_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report46()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report46_check_table1()
        report.enter_admin_report_select_the_report46_check_table2()
        report.enter_admin_report_select_the_report46_check_table3()
        report.enter_admin_report_select_the_report46_check_table4()
        report.enter_admin_report_select_the_report46_check_table5()
        report.enter_admin_report_select_the_report46_check_table6()
        report.enter_admin_report_select_the_report46_check_table7()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report47()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report47_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report48()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        # report.enter_admin_report_select_the_report48_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report49()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report49_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report50()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report50_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report51()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report51_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report52()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report52_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report53()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report53_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report54()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report54_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report55()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report55_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report56()
        report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report56_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report57()
        report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report57_check_table()
        report.enter_admin_report_arian_management_report5_created_by_check()
        report.enter_admin_report_select_the_report57_check_filter()

        print("############################################")

    @classmethod
    def tearDownClass(cls) -> None:
        sleep(5)
        cls.driver.close()
        cls.driver.quit()
