from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
from time import sleep

from Locators import *
from Pages.Admin.Report import Report
from Pages.Login import LoginPage
import unittest


# driver = webdriver.Chrome(ChromeDriverManager().install())
from selenium.webdriver.chrome.service import Service
service = Service()
options = webdriver.ChromeOptions()
# options.add_argument("--headless")

driver = webdriver.Chrome(service=service, options=options)


class Test_bpm(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.driver = driver
        cls.driver.maximize_window()
        cls.driver.implicitly_wait(5)

################### login_admin ###################

    def test01_login_admin(self):
        self.driver.get(base_url)
        login = LoginPage(driver=self.driver)
        login.enter_login_username(account_admin02)
        login.enter_login_btn_submit_next()
        login.enter_login_password(code_admin)
        login.enter_login_btn_submit()
        print("با موفقیت وارد پنل ادمین شد")
        print("############################################")

################### admin_report_select_the_reports ###################

    def test02_admin_report_select_the_reports(self):
        report = Report(driver=self.driver)
        report.enter_admin_report()
        report.enter_admin_report_select_the_report104()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report104_check_table1()
        report.enter_admin_report_select_the_report104_check_table2()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report105()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report105_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report106()
        report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report106_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report107()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report107_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report108()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report108_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report109()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report109_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report110()
        # report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report110_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report111()
        report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report111_check_table()
        report.enter_admin_report_select_the_report111_created_by_check()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report112()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report112_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report113()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report113_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report114()
        report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report114_check_table()
        a = report.enter_admin_report_select_the_report02_tn()
        report.enter_admin_report_reports_search_tn(a)
        report.enter_admin_report_select_the_report02_tn_assert_search()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report115()
        report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report115_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report116()
        report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report116_check_table()
        # report.enter_admin_report()
        # report.enter_admin_report_select_the_report117()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        # report.enter_admin_report_select_the_report117_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report118()
        report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report118_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report119()
        report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report119_check_table()
        report.enter_admin_report_select_the_report05_detail()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report120()
        report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report120_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report121()
        report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report121_check_table()
        a = report.enter_admin_report_select_the_report02_tn()
        report.enter_admin_report_reports_search_tn(a)
        report.enter_admin_report_select_the_report02_tn_assert_search()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report122()
        report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report122_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report123()
        # report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report123_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report124()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report124_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report125()
        report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report125_check_table()
        b = report.enter_admin_report_select_the_report75_tn()
        # report.enter_admin_report_reports_search_tn(b)
        # report.enter_admin_report_select_the_report02_tn_assert_search()
        report.enter_admin_report_reports_search_tn("")
        report.enter_admin_report_select_the_report09_status_check()
        report.enter_admin_report_select_the_report20_destination_filter()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report126()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report126_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report127()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report127_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report129()
        report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report129_check_table()

        print("############################################")

    @classmethod
    def tearDownClass(cls) -> None:
        sleep(5)
        cls.driver.close()
        cls.driver.quit()
