from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
from time import sleep

from Locators import *
from Pages.Admin.Report import Report
from Pages.Login import LoginPage
import unittest


# driver = webdriver.Chrome(ChromeDriverManager().install())
from selenium.webdriver.chrome.service import Service
service = Service()
options = webdriver.ChromeOptions()
# options.add_argument("--headless")

driver = webdriver.Chrome(service=service, options=options)


class Test_bpm(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.driver = driver
        cls.driver.maximize_window()
        cls.driver.implicitly_wait(5)

################### login_admin ###################

    def test01_login_admin(self):
        self.driver.get(base_url)
        login = LoginPage(driver=self.driver)
        login.enter_login_username(account_admin02)
        login.enter_login_btn_submit_next()
        login.enter_login_password(code_admin)
        login.enter_login_btn_submit()
        print("با موفقیت وارد پنل ادمین شد")
        print("############################################")

################### admin_report_select_the_reports ###################

    def test02_admin_report_select_the_reports(self):
        report = Report(driver=self.driver)
        report.enter_admin_report()
        report.enter_admin_report_select_the_report130()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report130_check_table()
        b = report.enter_admin_report_select_the_report02_tn()
        report.enter_admin_report_reports_search_tn(b)
        # report.enter_admin_report_select_the_report02_tn_assert_search()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report131()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report131_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report132()
        report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report132_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report133()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report133_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report134()
        report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report134_check_table()
        report.enter_admin_report_select_the_report134_cost_type()
        report.enter_admin_report_select_the_report134_other_inquery_type()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report135()
        report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report135_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report136()
        report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report136_check_table()
        b = report.enter_admin_report_select_the_report02_tn()
        # report.enter_admin_report_reports_search_tn(b)
        # report.enter_admin_report_select_the_report22_tn_assert_search()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report137()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report137_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report138()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report138_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report139()
        report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report139_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report140()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report140_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report141()
        report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report141_check_table()
        # b = report.enter_admin_report_select_the_report02_tn()
        report.enter_admin_report_reports_search_tn("")
        # report.enter_admin_report_select_the_report22_tn_assert_search()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report142()
        report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report142_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report143()
        report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report143_check_table()
        e = report.enter_admin_report_select_the_report02_tn()
        report.enter_admin_report_reports_search_tn(e)
        # report.enter_admin_report_select_the_report26_tn_assert_search()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report144()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report144_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report145()
        report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report145_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report146()
        report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report146_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report147()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        # report.enter_admin_report_select_the_report147_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report148()
        report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report148_check_table()
        report.enter_admin_report_select_the_report15_agency_id()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report149()
        report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report149_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report150()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report150_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report151()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report151_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report152()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report152_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report153()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report153_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report154()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report154_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report155()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report155_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report156()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report156_check_table1()
        report.enter_admin_report_select_the_report46_check_table2()
        report.enter_admin_report_select_the_report46_check_table3()
        report.enter_admin_report_select_the_report46_check_table4()
        report.enter_admin_report_select_the_report156_check_table5()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report157()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report157_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report158()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report158_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report159()
        report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report159_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report160()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report160_check_table()
        report.enter_admin_report_select_the_report160_check_table01()
        report.enter_admin_report_select_the_report160_check_table02()
        report.enter_admin_report_select_the_report160_check_table03()
        report.enter_admin_report_select_the_report160_check_table04()
        report.enter_admin_report_select_the_report160_check_table05()
        report.enter_admin_report_select_the_report160_check_table06()
        report.enter_admin_report_select_the_report160_check_table07()
        report.enter_admin_report_select_the_report160_check_table08()
        report.enter_admin_report_select_the_report160_check_table09()
        report.enter_admin_report_select_the_report160_check_table10()
        report.enter_admin_report_select_the_report160_check_table11()
        report.enter_admin_report_select_the_report160_check_table12()
        report.enter_admin_report_select_the_report160_check_table13()
        print("############################################")

    @classmethod
    def tearDownClass(cls) -> None:
        sleep(5)
        cls.driver.close()
        cls.driver.quit()
