from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
from time import sleep

from Locators import *
from Pages.Admin.Report import Report
from Pages.Login import LoginPage
import unittest


# driver = webdriver.Chrome(ChromeDriverManager().install())
from selenium.webdriver.chrome.service import Service
service = Service()
options = webdriver.ChromeOptions()
# options.add_argument("--headless")

driver = webdriver.Chrome(service=service, options=options)


class Test_bpm(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.driver = driver
        cls.driver.maximize_window()
        cls.driver.implicitly_wait(5)

################### login_admin ###################

    def test01_login_admin(self):
        self.driver.get(base_url)
        login = LoginPage(driver=self.driver)
        login.enter_login_username(account_admin02)
        login.enter_login_btn_submit_next()
        login.enter_login_password(code_admin)
        login.enter_login_btn_submit()
        print("با موفقیت وارد پنل ادمین شد")
        print("############################################")

################### admin_report_select_the_reports ###################

    def test02_admin_report_select_the_reports(self):
        report = Report(driver=self.driver)
        report.enter_admin_report()
        report.enter_admin_report_select_the_report76()
        report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report76_check_table()
        a = report.enter_admin_report_select_the_report02_tn()
        report.enter_admin_report_reports_search_tn(a)
        # report.enter_admin_report_select_the_report22_tn_assert_search()
        report.enter_admin_report_reports_search_tn("")
        report.enter_admin_report_select_the_report76_status_check()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report77()
        report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report77_check_table1()
        report.enter_admin_report_select_the_report77_check_table2()
        b = report.enter_admin_report_select_the_report02_tn()
        report.enter_admin_report_reports_search_tn(b)
        report.enter_admin_report_select_the_report26_tn_assert_search()
        report.enter_admin_report_reports_search_tn("")
        sleep(1)
        report.enter_admin_report_select_the_report77_status_check()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report78()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report78_check_table1()
        report.enter_admin_report_select_the_report78_check_table2()
        report.enter_admin_report_select_the_report78_check_table3()
        report.enter_admin_report_select_the_report78_check_table4()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report79()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report79_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report80()
        report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report80_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report81()
        report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report81_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report82()
        report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report82_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report83()
        report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report83_check_table()
        report.enter_admin_report_arian_management_report5_created_by_check()
        report.enter_admin_report_select_the_report83_by_check()
        report.enter_admin_report_select_the_report83_users_filter()
        report.enter_admin_report_select_the_report83_agency_check()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report84()
        report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report84_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report85()
        report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report85_check_table()
        c = report.enter_admin_report_select_the_report75_tn()
        report.enter_admin_report_reports_search_tn(c)
        report.enter_admin_report_select_the_report02_tn_assert_search()
        report.enter_admin_report_reports_search_tn("")
        report.enter_admin_report_select_the_report09_status_check()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report86()
        report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report86_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report87()
        report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report87_check_table()
        d = report.enter_admin_report_select_the_report34_tn()
        report.enter_admin_report_reports_search_tn(d)
        report.enter_admin_report_select_the_report02_tn_assert_search()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report88()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report88_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report89()
        report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report89_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report90()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report90_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report91()
        report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report91_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report92()
        # report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report92_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report93()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report93_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report94()
        # report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report94_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report95()
        # report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report95_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report96()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report96_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report97()
        # report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report97_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report98()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report98_check_table1()
        report.enter_admin_report_select_the_report98_check_table2()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report100()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report100_check_table1()
        report.enter_admin_report_select_the_report100_check_table2()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report101()
        report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report101_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report102()
        # report.enter_admin_report_filter()
        # report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report102_check_table()
        report.enter_admin_report()
        report.enter_admin_report_select_the_report103()
        report.enter_admin_report_filter()
        report.enter_admin_report_check_excel()
        report.enter_admin_report_select_the_report103_check_table()
        report.enter_admin_report_select_the_report103_customer_manager()

        print("############################################")

    @classmethod
    def tearDownClass(cls) -> None:
        sleep(5)
        cls.driver.close()
        cls.driver.quit()
